// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA3ot-KAjlpWauwMvbl_KHS7oH7tyPcJM',
    appId: '1:918065261494:web:143a378366b5abbbcfaf17',
    messagingSenderId: '918065261494',
    projectId: 'airplane-36ac1',
    authDomain: 'airplane-36ac1.firebaseapp.com',
    storageBucket: 'airplane-36ac1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTVZmaTVA2nslRqvzO1Jzlw5VMJ8WZg1o',
    appId: '1:918065261494:android:3a01122e536a70d1cfaf17',
    messagingSenderId: '918065261494',
    projectId: 'airplane-36ac1',
    storageBucket: 'airplane-36ac1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2qXsiO6MgCjDVolkQluRRdbFqNeGcmxY',
    appId: '1:918065261494:ios:2161c949fe8efa5bcfaf17',
    messagingSenderId: '918065261494',
    projectId: 'airplane-36ac1',
    storageBucket: 'airplane-36ac1.appspot.com',
    iosBundleId: 'com.example.airplaneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2qXsiO6MgCjDVolkQluRRdbFqNeGcmxY',
    appId: '1:918065261494:ios:79940ab9c4b7fd6ccfaf17',
    messagingSenderId: '918065261494',
    projectId: 'airplane-36ac1',
    storageBucket: 'airplane-36ac1.appspot.com',
    iosBundleId: 'com.example.airplaneApp.RunnerTests',
  );
}
